"""Generate the WebGL preview from the typed, shared Tron WGSL subset."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = (root / 'src-tauri/shaders/tron.wgsl').read_text()
source = source.replace('params.reactive', 'u_reactive').replace('params.spatial.x', 'u_tronTime')
for wgsl, glsl in [('vec4<f32>', 'vec4'), ('vec2<f32>', 'vec2'), ('vec3<f32>', 'vec3'), ('f32', 'float'), ('u32', 'int')]:
    source = source.replace(wgsl, glsl)
source = re.sub(r'fn (\w+)\((.*?)\) -> (\w+) \{',
                lambda m: m[3]+' '+m[1]+'('+re.sub(r'(\w+): (\w+)', r'\2 \1', m[2])+') {', source)
source = re.sub(r'\b(?:let|var) (\w+): (\w+)', r'\2 \1', source)
source = re.sub(r'(\d+)u\b', r'\1', source)
source = source.replace('atan2(', 'atan(')
source = re.sub(r'\bif ([^{]+) \{', r'if (\1) {', source)
source = source.replace('recent_signal(', 'tron_recent_signal(')
source = 'vec4 tron_recent_signal(float age) { return vec4(0.0); }\n' + source
source = 'vec2 rotate2(vec2 p, float a) { return mat2(cos(a), -sin(a), sin(a), cos(a)) * p; }\n'+source
(root / 'app/src/visuals/tronShader.ts').write_text('// Generated by scripts/sync-tron-shader.py; edit tron.wgsl.\nexport const tronShader = `\n'+source+'`;\n')
