"""Generate small, single-look WebGL previews from the shared Tron WGSL subset."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = (root / 'src-tauri/shaders/tron.wgsl').read_text()
source = source.replace('params.reactive', 'u_reactive').replace('params.spatial.x', 'u_tronTime').replace('params.chromatic.w', 'u_dimension')
for wgsl, glsl in [('vec4<f32>', 'vec4'), ('vec2<f32>', 'vec2'), ('vec3<f32>', 'vec3'), ('f32', 'float'), ('u32', 'int')]:
    source = source.replace(wgsl, glsl)
source = re.sub(r'fn (\w+)\((.*?)\) -> (\w+) \{',
                lambda m: m[3]+' '+m[1]+'('+re.sub(r'(\w+): (\w+)', r'\2 \1', m[2])+') {', source)
source = re.sub(r'\b(?:let|var) (\w+): (\w+)', r'\2 \1', source)
source = re.sub(r'(\d+)u\b', r'\1', source)
source = source.replace('atan2(', 'atan(')
source = re.sub(r'\bif ([^{]+) \{', r'if (\1) {', source)
source = source.replace('recent_signal(', 'tron_recent_signal(')
source = 'vec4 tron_recent_signal(float age) { return vec4(0.0); }\n' + source
source = 'vec2 rotate2(vec2 p, float a) { return mat2(cos(a), -sin(a), sin(a), cos(a)) * p; }\n'+source


def block_end(text, opening):
    depth = 1
    for index in range(opening + 1, len(text)):
        depth += (text[index] == '{') - (text[index] == '}')
        if depth == 0:
            return index
    raise ValueError('Unclosed shader block')


def specialize(text, look):
    """Remove look branches before the driver sees them, including nested branches.

    Driver constant folding alone still feeds the whole library to ANGLE's
    translator. Fail on unsupported look conditions instead of silently drifting
    from WGSL. Other conditions and loop bounds are preserved verbatim.
    """
    match = re.search(r'\bif \((look\b[^)]*)\) \{', text)
    if not match:
        return text
    start = match.start()
    selected = ''
    matched = False
    while True:
        condition = match[1]
        if not re.fullmatch(r'look == \d+(?: \|\| look == \d+)*', condition):
            raise ValueError(f'Unsupported look condition: {condition}')
        opening = match.end() - 1
        end = block_end(text, opening) + 1
        if not matched and look in map(int, re.findall(r'\d+', condition)):
            selected = text[opening:end]
            matched = True
        following = re.match(r'\s*else if \((look\b[^)]*)\) \{', text[end:])
        if following:
            # Use a match into the full text so its offsets remain absolute.
            match = re.compile(r'\s*else if \((look\b[^)]*)\) \{').match(text, end)
            continue
        fallback = re.match(r'\s*else \{', text[end:])
        if fallback:
            opening = end + fallback.end() - 1
            end = block_end(text, opening) + 1
            if not matched:
                selected = text[opening:end]
        break
    return text[:start] + specialize(selected, look) + specialize(text[end:], look)


helpers, body = source.split('vec3 tron_look', 1)
body = 'vec3 tron_look' + body.split('int tron_variant', 1)[0]
body = body.replace('vec2 p, int look, float t', 'vec2 p, float t')
looks = [specialize(body, look) for look in range(16)]
assert all(not re.search(r'\blook\b', look) for look in looks)
output = '// Generated by scripts/sync-tron-shader.py; edit tron.wgsl.\n'
output += '// Only one specialized look is submitted to the browser GPU compiler.\n'
output += 'export const tronHelpers = `\n' + helpers + '`;\n'
output += 'export const tronLookShaders = [\n' + ''.join('`\n' + look + '`,\n' for look in looks) + '] as const;\n'
(root / 'app/src/visuals/tronShader.ts').write_text('\n'.join(line.rstrip() for line in output.splitlines()) + '\n')
