// Generated by scripts/sync-tron-shader.py; edit tron.wgsl.
export const tronShader = `
vec2 rotate2(vec2 p, float a) { return mat2(cos(a), -sin(a), sin(a), cos(a)) * p; }
// Shared with the ambient preview via scripts/sync-tron-shader.py.
// Analytic distance fields: bounded work, filtered edges, no textures or particles.
float tron_glow(float distance, float width) {
    float aa = max(fwidth(distance), 0.0012);
    return (1.0 - smoothstep(width, width + aa, abs(distance)))
        + 0.32 * exp(-abs(distance) / (width * 4.0 + aa));
}

float tron_segment(vec2 p, vec2 a, vec2 b) {
    vec2 v = b - a;
    return length(p - a - v * clamp(dot(p - a, v) / max(dot(v, v), 0.0001), 0.0, 1.0));
}

vec3 tron_look(vec2 p, int look, float t) {
    float bass = u_reactive.x;
    float mids = u_reactive.y;
    float highs = u_reactive.z;
    vec3 cyan = vec3(0.015, 0.78, 1.0);
    vec3 orange = vec3(1.0, 0.24, 0.025);
    vec3 blue = vec3(0.08, 0.18, 0.95);
    vec3 light = vec3(0.001, 0.004, 0.012);
    float r = length(p);
    float tick = t * 1.6;
    if (look == 0 || look == 1 || look == 8) {
        // Grid highway, light-cycle tracks, and an elevated neon city.
        float horizon = p.y + 0.18;
        float depth = 1.0 / max(abs(horizon), 0.035);
        vec2 world = vec2(p.x * depth, depth + tick);
        vec2 cell = abs(fract(world * 0.5) - 0.5);
        float grid = tron_glow(min(cell.x, cell.y), 0.012);
        float fade = smoothstep(0.035, 0.25, horizon) / (1.0 + depth * 0.035);
        light += cyan * grid * fade * (0.55 + bass * 0.6);
        light += blue * exp(-abs(horizon) * 20.0) * 0.35;
        if (look == 0) {
            float sun = tron_glow(length(p - vec2(0.0, -0.43)) - 0.22 - bass * 0.025, 0.009);
            light += orange * sun;
        }
        if (look == 1) {
            for (int i = 0; i < 6; i += 1) {
                float fi = float(i);
                float lane = (fi - 2.5) * 1.65 + sin(t * 0.3 + fi) * 0.35;
                float trail = tron_glow(world.x - lane, 0.028) * (0.35 + 0.65 * pow(fract(world.y * 0.08 - t * 0.2 + fi * 0.17), 3.0));
                light += mix(cyan, orange, float(i % 2)) * trail * fade;
            }
        }
        if (look == 8) {
            for (int i = 0; i < 18; i += 1) {
                float fi = float(i);
                float x = (fi - 8.5) * 0.19;
                float height = 0.12 + 0.5 * fract(sin(fi * 32.7) * 437.1) + mids * 0.07;
                vec2 box = abs(p - vec2(x, -0.18 - height * 0.5)) - vec2(0.066, height * 0.5);
                float edge = abs(max(box.x, box.y));
                light += mix(cyan, orange, float(i % 3) * 0.35) * tron_glow(edge, 0.003) * 0.75;
            }
        }
    } else if (look == 2 || look == 3 || look == 9) {
        // Rectangular gates, hexagonal corridor, and a twisting laser helix.
        for (int i = 0; i < 18; i += 1) {
            float fi = float(i);
            float z = fract((fi - t * 1.1) / 18.0);
            float scale = 0.08 + z * z * 2.5;
            float rotation = mids * sin(fi * 0.4 + t) * 0.12;
            vec2 q = rotate2(p, rotation);
            float d = max(abs(q.x) * 0.72, abs(q.y)) - scale;
            if (look == 3) {
                d = max(abs(q.y), abs(q.x) * 0.866025 + abs(q.y) * 0.5) - scale;
            }
            if (look == 9) {
                q = rotate2(p, fi * 0.19 + t * 0.22);
                d = max(abs(q.x), abs(q.y)) - scale;
            }
            light += mix(cyan, orange, float(i % 4) / 3.0) * tron_glow(d - bass * z * 0.06, 0.003 + z * 0.003) * smoothstep(0.0, 0.15, z) * (1.0 - z * 0.6);
        }
    } else if (look == 4) {
        // Identity discs: orbiting double rings with broken orange arcs.
        for (int i = 0; i < 5; i += 1) {
            float fi = float(i);
            vec2 center = vec2(cos(fi * 2.4 + t * 0.24), sin(fi * 2.4 + t * 0.24)) * fi * 0.18;
            vec2 q = p - center;
            float radius = 0.19 + fi * 0.027 + bass * 0.025;
            float edge = min(abs(length(q) - radius), abs(length(q) - radius * 0.84));
            light += mix(cyan, orange, float(i % 2)) * tron_glow(edge, 0.004);
        }
    } else if (look == 5) {
        // Circuit board with right-angle traces and moving signal nodes.
        for (int i = 0; i < 16; i += 1) {
            float fi = float(i);
            float y = (fi - 7.5) * 0.13;
            float bend = sin(fi * 4.7) * 0.85;
            vec2 a = vec2(-2.0, y);
            vec2 b = vec2(bend, y);
            vec2 c = vec2(bend + 0.22, y + 0.1);
            float d = min(tron_segment(p, a, b), tron_segment(p, b, c));
            float trace = min(d, tron_segment(p, c, vec2(2.0, y + 0.1)));
            float packet = exp(-pow((p.x - (fract(t * 0.12 + fi * 0.137) * 4.0 - 2.0)) * 12.0, 2.0));
            light += mix(cyan, orange, float(i % 3) * 0.5) * tron_glow(trace, 0.0025) * (0.25 + packet * (1.0 + highs));
        }
    } else if (look == 6) {
        // Arena: concentric floor rings and a crown of laser pillars.
        vec2 q = vec2(p.x, (p.y - 0.3) * 2.5);
        light += cyan * tron_glow(abs(fract(length(q) * 3.0 - t * 0.3) - 0.5), 0.016) * exp(-length(q) * 0.8);
        for (int i = 0; i < 17; i += 1) {
            float fi = float(i);
            float x = (fi - 8.0) * 0.16;
            float height = 0.18 + 0.45 * (0.5 + 0.5 * sin(fi * 0.8 + t)) + bass * 0.23;
            light += mix(cyan, orange, float(i % 2)) * tron_glow(tron_segment(p, vec2(x, 0.1), vec2(x, -height)), 0.004);
        }
    } else if (look == 7) {
        // Solar sail: opposing fans of thin laser beams.
        for (int i = 0; i < 24; i += 1) {
            float fi = float(i);
            vec2 end = vec2((fi - 11.5) * 0.16, -0.7 + sin(fi * 0.3 + t) * (0.12 + mids * 0.25));
            light += mix(cyan, orange, fi / 23.0) * tron_glow(tron_segment(p, vec2(sin(t * 0.2) * 0.5, 0.8), end), 0.0025) * 0.65;
        }
    } else if (look == 10) {
        // Data rain: segmented falling columns, each with its own speed.
        float column = floor(p.x * 22.0);
        float seed = fract(sin(column * 73.1) * 437.3);
        float head = fract(p.y * 0.35 - t * (0.12 + seed * 0.18) + seed);
        float x = abs(fract(p.x * 22.0) - 0.5);
        float dash = 1.0 - smoothstep(0.26, 0.42, abs(fract(p.y * 24.0) - 0.5));
        light += mix(cyan, orange, step(0.8, seed)) * tron_glow(x, 0.07) * dash * pow(head, 8.0) * (1.0 + highs);
    } else {
        // Reactor iris: concentric machinery and rotating segmented spokes.
        vec2 q = rotate2(p, t * 0.18);
        float spokes = abs(sin(atan(q.y, q.x) * 12.0)) * max(r, 0.03);
        float ring = min(abs(r - 0.3 - bass * 0.04), min(abs(r - 0.58), abs(r - 0.75)));
        light += cyan * tron_glow(ring, 0.006);
        light += orange * tron_glow(spokes, 0.007) * smoothstep(0.32, 0.38, r) * (1.0 - smoothstep(0.68, 0.74, r));
        light += blue * exp(-r * 8.0) * (0.5 + bass);
    }
    return light * (0.9 + u_reactive.w * 0.35) + orange * light.b * highs * 0.15;
}

vec3 tron_scene(int id, vec2 uv) {
    float t = u_tronTime;
    vec2 p = rotate2(uv, u_reactive.y * 0.06) * (1.0 - u_reactive.x * 0.045);
    if (id != 32) { return tron_look(p, id - 33, t); }
    // Long dwell, then a gentle dissolve; integrated motion never jumps on hits.
    float chapter = t / 8.0;
    int current = int(floor(chapter)) % 12;
    float blend = smoothstep(0.8, 1.0, fract(chapter));
    vec3 outgoing = tron_look(p, current, t);
    if (blend <= 0.0) { return outgoing; }
    return mix(outgoing, tron_look(p, (current + 1) % 12, t), blend);
}
`;
