// Generated by scripts/sync-tron-shader.py; edit tron.wgsl.
export const tronShader = `
vec2 rotate2(vec2 p, float a) { return mat2(cos(a), -sin(a), sin(a), cos(a)) * p; }
vec4 tron_recent_signal(float age) { return vec4(0.0); }
// Shared with the ambient preview via scripts/sync-tron-shader.py.
// Analytic distance fields: bounded work, filtered edges, no textures or particles.
// Position-delayed audio keeps a hit traveling after its live envelope has fallen.
vec4 tron_signal(float age) {
    return clamp(tron_recent_signal(age) * 1.15 + u_reactive * 0.25, vec4(0.0), vec4(1.0));
}

float tron_glow(float distance, float width) {
    float aa = max(fwidth(distance), 0.0012);
    return (1.0 - smoothstep(width, width + aa, abs(distance)))
        + 0.32 * exp(-abs(distance) / (width * 4.0 + aa));
}

float tron_segment(vec2 p, vec2 a, vec2 b) {
    vec2 v = b - a;
    return length(p - a - v * clamp(dot(p - a, v) / max(dot(v, v), 0.0001), 0.0, 1.0));
}

vec3 tron_look(vec2 p, int look, float t) {
    float bass = u_reactive.x;
    float mids = u_reactive.y;
    float highs = u_reactive.z;
    vec3 cyan = vec3(0.015, 0.78, 1.0);
    vec3 orange = vec3(1.0, 0.24, 0.025);
    vec3 blue = vec3(0.08, 0.18, 0.95);
    vec3 light = vec3(0.001, 0.004, 0.012);
    float r = length(p);
    float tick = t * 1.6;
    if (look == 0 || look == 1 || look == 8) {
        // Grid highway, light-cycle tracks, and an elevated neon city.
        vec4 road_signal = tron_signal(clamp((1.0 - p.y) * 0.52, 0.0, 0.95));
        float lift = road_signal.x * sin(p.y * 5.0 - t * 0.5) * 0.19;
        float horizon = p.y + 0.18 + lift;
        float depth = 1.0 / max(abs(horizon), 0.035);
        float steering = road_signal.y * sin(depth * 0.24 + t * 0.35) * 1.7;
        vec2 world = vec2(p.x * depth + steering, depth + tick + road_signal.x * 2.6);
        float fracture = sin(floor(world.y * 0.5) * 2.1) * road_signal.z * 1.2;
        vec2 cell = abs(fract((world + vec2(fracture, 0.0)) * 0.5) - 0.5);
        float grid = tron_glow(min(cell.x, cell.y), 0.012);
        float fade = smoothstep(0.035, 0.25, horizon) / (1.0 + depth * 0.035);
        light += cyan * grid * fade * (0.55 + bass * 0.6);
        light += blue * exp(-abs(horizon) * 20.0) * 0.35;
        if (look == 0) {
            vec2 sun_center = vec2(sin(t * 0.3) * mids * 0.3, -0.43);
            float sun = tron_glow(length(p - sun_center) - 0.22, 0.009);
            light += orange * sun;
            float wake = tron_glow(road_signal.x - 0.45, 0.05) * road_signal.x;
            light += cyan * wake * fade * 0.55;
        }
        if (look == 1) {
            for (int i = 0; i < 6; i += 1) {
                float fi = float(i);
                vec4 rider = tron_signal(fi * 0.12);
                float lane = (fi - 2.5) * 1.65 + sin(t * 0.3 + fi) * 0.35
                    + sign(sin(fi * 7.0)) * smoothstep(0.15, 0.75, rider.y) * 1.8
                    + rider.z * sin(fi * 2.5) * 0.9;
                float head = fract(world.y * 0.08 - t * 0.2 + fi * 0.17 + rider.x * 0.24);
                float trail = tron_glow(world.x - lane, 0.028) * (0.18 + 0.82 * pow(head, 3.0));
                float bike = tron_glow(world.x - lane, 0.1) * exp(-pow((head - 0.94) * 35.0, 2.0));
                light += mix(cyan, orange, float(i % 2)) * (trail + bike * (0.8 + rider.z)) * fade;
            }
        }
        if (look == 8) {
            for (int i = 0; i < 18; i += 1) {
                float fi = float(i);
                vec4 tower = tron_signal(abs(fi - 8.5) * 0.1);
                float x = (fi - 8.5) * 0.19 + tower.y * sin(fi * 1.7) * 0.1;
                float height = 0.12 + 0.5 * fract(sin(fi * 32.7) * 437.1) + tower.x * 0.38;
                vec2 tower_p = p + vec2(sin(p.y * 8.0 + fi) * tower.y * 0.035, tower.z * sin(fi * 5.0) * 0.1);
                vec2 box = abs(tower_p - vec2(x, -0.18 - height * 0.5)) - vec2(0.066, height * 0.5);
                float edge = abs(max(box.x, box.y));
                light += mix(cyan, orange, float(i % 3) * 0.35) * tron_glow(edge, 0.003) * 0.75;
            }
        }
    } else if (look == 2 || look == 3 || look == 9) {
        // Rectangular gates, hexagonal corridor, and a twisting laser helix.
        for (int i = 0; i < 18; i += 1) {
            float fi = float(i);
            float z = fract((fi - t * 1.1) / 18.0);
            vec4 gate = tron_signal((1.0 - z) * 0.92);
            float scale = 0.08 + z * z * 2.5 + gate.x * z * 0.65;
            float rotation = gate.y * sin(fi * 0.4 + t) * 0.85;
            vec2 center = vec2(sin(z * 5.0 + t * 0.25), cos(z * 4.0)) * gate.y * z * 0.45;
            vec2 q = rotate2(p - center, rotation);
            q += vec2(sign(q.y), sign(q.x)) * gate.z * z * 0.13;
            float d = max(abs(q.x) * 0.72, abs(q.y)) - scale;
            if (look == 3) {
                d = max(abs(q.y), abs(q.x) * 0.866025 + abs(q.y) * 0.5) - scale;
            }
            if (look == 9) {
                q = rotate2(q, fi * 0.19 + t * 0.22 + gate.y * z * 1.8);
                d = max(abs(q.x), abs(q.y)) - scale;
            }
            light += mix(cyan, orange, float(i % 4) / 3.0) * tron_glow(d, 0.003 + z * 0.003) * smoothstep(0.0, 0.15, z) * (1.0 - z * 0.6);
        }
    } else if (look == 4) {
        // Thrown discs accelerate across the arena, with position-delayed echoes.
        for (int i = 0; i < 7; i += 1) {
            float fi = float(i);
            for (int echo = 0; echo < 3; echo += 1) {
                float lag = float(echo) * 0.09;
                vec4 disc = tron_signal(fi * 0.08 + lag);
                float orbit = fi * 2.4 + (t - lag) * 0.4 + disc.y * 1.5;
                float flight = fi * 0.12 + disc.x * 0.7;
                vec2 center = vec2(cos(orbit) * 1.55, sin(orbit)) * flight;
                vec2 q = rotate2(p - center, orbit);
                float shard_angle = floor(atan(q.y, q.x) * 3.0) / 3.0;
                q -= vec2(cos(shard_angle), sin(shard_angle)) * disc.z * 0.16;
                float radius = 0.14 + fi * 0.017;
                float disc_r = length(q * vec2(1.0, 1.0 + disc.y * 1.7));
                float edge = min(abs(disc_r - radius), abs(disc_r - radius * 0.84));
                float cut = 1.0 - disc.z * smoothstep(0.25, 0.6, sin(atan(q.y, q.x) * 5.0 + fi));
                light += mix(cyan, orange, float(i % 2)) * tron_glow(edge, 0.0035) * cut / (1.0 + float(echo) * 3.0);
            }
        }
    } else if (look == 5) {
        // Circuit board with right-angle traces and moving signal nodes.
        for (int i = 0; i < 16; i += 1) {
            float fi = float(i);
            vec4 circuit = tron_signal(fi * 0.052);
            float y = (fi - 7.5) * 0.13 + circuit.x * sin(fi * 2.0) * 0.065 + circuit.y * sin(fi * 0.7) * 0.18;
            vec2 trace_p = p + vec2(0.0, circuit.z * sin(p.x * 6.0 + fi) * 0.09);
            float bend = sin(fi * 4.7) * 0.85 + circuit.y * sin(fi * 1.3) * 0.8;
            vec2 a = vec2(-2.0, y);
            vec2 b = vec2(bend, y);
            vec2 c = vec2(bend + 0.22 + circuit.y * 0.28, y + 0.1 + circuit.x * 0.15);
            float d = min(tron_segment(trace_p, a, b), tron_segment(trace_p, b, c));
            float trace = min(d, tron_segment(trace_p, c, vec2(2.0, y + 0.1 + circuit.x * 0.15)));
            float packet = exp(-pow((p.x - (fract(t * 0.12 + fi * 0.137 + circuit.z * 0.42) * 4.0 - 2.0)) * 12.0, 2.0));
            light += mix(cyan, orange, float(i % 3) * 0.5) * tron_glow(trace, 0.0025) * (0.25 + packet * (1.0 + highs));
        }
    } else if (look == 6) {
        // Arena: concentric floor rings and a crown of laser pillars.
        vec4 arena = tron_signal(clamp(length(p) * 0.65, 0.0, 0.95));
        vec2 q = vec2(p.x + arena.y * sin(p.y * 6.0) * 0.4, (p.y - 0.3) * 2.5);
        light += cyan * tron_glow(abs(fract(length(q) * 3.0 - t * 0.3) - 0.5), 0.016) * exp(-length(q) * 0.8);
        for (int i = 0; i < 17; i += 1) {
            float fi = float(i);
            vec4 pillar = tron_signal(abs(fi - 8.0) * 0.1);
            float x = (fi - 8.0) * 0.16;
            float height = 0.18 + 0.18 * (0.5 + 0.5 * sin(fi * 0.8 + t)) + pillar.x * 0.65;
            vec2 tip = vec2(x + pillar.y * sin(fi) * 0.65, -height);
            float beam = tron_glow(tron_segment(p, vec2(x, 0.1), tip), 0.004);
            float bolt = tron_glow(tron_segment(p, tip, tip + vec2(sin(fi), -1.0) * pillar.z * 0.55), 0.008) * pillar.z;
            light += mix(cyan, orange, float(i % 2)) * (beam + bolt);
        }
    } else if (look == 7) {
        // Solar sail: opposing fans of thin laser beams.
        for (int i = 0; i < 24; i += 1) {
            float fi = float(i);
            vec4 sail = tron_signal(fi * 0.035);
            vec2 end = vec2((fi - 11.5) * (0.16 + sail.x * 0.07), -0.7 + sin(fi * 0.3 + t) * (0.12 + sail.y * 0.6));
            vec2 origin = vec2(sin(t * 0.2) * 0.5 + sail.y * sin(fi * 0.35) * 0.9, 0.8 - sail.x * 0.35);
            float tear = 1.0 - sail.z * smoothstep(0.2, 0.5, sin(p.y * 30.0 + fi));
            light += mix(cyan, orange, fi / 23.0) * tron_glow(tron_segment(p, origin, end), 0.0025) * 0.65 * tear;
        }
    } else if (look == 10) {
        // Data rain: segmented falling columns, each with its own speed.
        vec4 rain = tron_signal(clamp((p.y + 1.0) * 0.42, 0.0, 0.9));
        float swept = p.x + rain.y * sin(p.y * 4.0 + t) * 0.3;
        float column = floor(swept * 22.0);
        float seed = fract(sin(column * 73.1) * 437.3);
        float head = fract(p.y * 0.35 - t * (0.12 + seed * 0.18) + seed - rain.x * (0.15 + seed * 0.35));
        float x = abs(fract((swept + rain.z * sin(column) * 0.045) * 22.0) - 0.5);
        float dash = 1.0 - smoothstep(0.26, 0.42, abs(fract((p.y - rain.z * seed * 0.4) * 24.0) - 0.5));
        light += mix(cyan, orange, step(0.8, seed)) * tron_glow(x, 0.07) * dash * pow(head, 8.0) * (1.0 + highs);
    } else if (look == 11) {
        // Mechanical iris: independent articulated blades, opening and latching.
        light += cyan * tron_glow(abs(r - 0.75), 0.006) * 0.45;
        for (int i = 0; i < 24; i += 1) {
            float fi = float(i);
            vec4 blade = tron_signal(fi * 0.035);
            float a = fi / 24.0 * 6.2831853 + t * 0.18 + blade.y * 0.7;
            float opening = 0.22 + blade.x * 0.3;
            float hinge = a + blade.y * 0.85;
            vec2 eject = vec2(cos(a + 0.8), sin(a + 0.8)) * blade.z * 0.3;
            vec2 inner = vec2(cos(hinge), sin(hinge)) * opening + eject;
            vec2 outer = vec2(cos(a), sin(a)) * (0.68 + blade.z * 0.24) + eject;
            float rib = tron_glow(tron_segment(p, inner, outer), 0.005);
            float ring_tip = tron_glow(length(p - inner) - 0.014, 0.003);
            light += (orange * rib + cyan * ring_tip) * 1.6;
        }
        light += blue * exp(-r * 8.0) * 0.12;
    } else if (look == 12) {
        // Neon Mandala: articulated petals open in a traveling circular wave.
        for (int i = 0; i < 18; i += 1) {
            float fi = float(i);
            vec4 signal = tron_signal(fi * 0.045);
            float a = fi * 6.2831853 / 18.0 + t * 0.12 + signal.y * 0.5;
            vec2 q = rotate2(p, a);
            float bend = signal.y * sin(q.x * 5.0 + fi) * 0.18;
            vec2 petal = vec2(q.x - 0.4 - signal.x * 0.3, (q.y + bend) * (3.0 + signal.z * 2.5));
            float edge = length(petal) - 0.34;
            light += mix(cyan, orange, float(i % 3) * 0.5) * tron_glow(edge, 0.004) * 0.75;
        }
    } else if (look == 13) {
        // Plasma Weave: crossing ribbons carry independent spectral ripples.
        for (int i = 0; i < 14; i += 1) {
            float fi = float(i);
            vec4 signal = tron_signal(clamp((p.x + 1.8) * 0.23 + fi * 0.013, 0.0, 0.95));
            float wave = sin(p.x * 2.6 + fi * 0.45 + t * 0.4) * (0.14 + signal.x * 0.25);
            float fold = sin(p.x * 5.0 - fi * 0.6) * signal.y * 0.2;
            float tear = sin(p.x * 16.0 + fi) * signal.z * 0.06;
            float y = (fi - 6.5) * 0.1 + wave + fold + tear;
            light += mix(cyan, vec3(0.9, 0.03, 0.75), fi / 13.0) * tron_glow(p.y - y, 0.005);
            light += orange * tron_glow(p.x - (fi - 6.5) * 0.15 - sin(p.y * 4.0 + fi + t * 0.25) * (0.2 + signal.y * 0.25), 0.003) * 0.35;
        }
    } else if (look == 14) {
        // Spectrum Bloom: nested flowers shear and split in different directions.
        float angle = atan(p.y, p.x);
        for (int i = 0; i < 12; i += 1) {
            float fi = float(i);
            vec4 signal = tron_signal(fi * 0.075);
            float petal = sin(angle * 6.0 + fi * 0.4 + t * 0.3 + signal.y * 2.5);
            float shape = 0.13 + fi * 0.07 + petal * (0.045 + signal.x * 0.12) + sin(angle * 18.0 + fi) * signal.z * 0.055;
            light += mix(vec3(0.95, 0.04, 0.5), cyan, fi / 11.0) * tron_glow(r - shape, 0.004);
        }
    } else {
        // Chromatic Moire: offset luminous interference sheets shear past each other.
        vec4 signal = tron_signal(clamp((p.y + 1.0) * 0.42, 0.0, 0.95));
        vec2 q = rotate2(p, 0.35 + signal.y * 0.65);
        float warp = sin(q.x * 3.0 + t * 0.25) * (0.12 + signal.x * 0.3);
        float a = sin((q.y + warp) * 27.0 + signal.z * sin(q.x * 11.0) * 2.0);
        float b = sin((q.x + sin(q.y * 2.3 - t * 0.2) * (0.2 + signal.y * 0.3)) * 24.0);
        light += cyan * tron_glow(a, 0.05) * 0.65;
        light += vec3(0.95, 0.03, 0.55) * tron_glow(b, 0.05) * 0.65;
    }
    return light * (0.9 + u_reactive.w * 0.35) + orange * light.b * highs * 0.15;
}

int tron_variant(int index, int dimension) {
    if (dimension == 1) {
        int i = index % 9;
        if (i == 0) { return 4; }
        if (i == 1) { return 5; }
        if (i == 2) { return 7; }
        if (i == 3) { return 10; }
        if (i == 4) { return 11; }
        return i + 7;
    }
    if (dimension == 2) {
        int i = index % 7;
        if (i < 4) { return i; }
        if (i == 4) { return 6; }
        if (i == 5) { return 8; }
        return 9;
    }
    return index % 16;
}

vec3 tron_scene(int id, vec2 uv) {
    float t = u_tronTime;
    if (id != 32) { return tron_look(uv, id - 33, t); }
    int dimension = int(round(u_dimension));
    float chapter = t / 8.0;
    int current = int(floor(chapter));
    float blend = smoothstep(0.8, 1.0, fract(chapter));
    vec3 outgoing = tron_look(uv, tron_variant(current, dimension), t);
    if (blend <= 0.0) { return outgoing; }
    return mix(outgoing, tron_look(uv, tron_variant(current + 1, dimension), t), blend);
}
`;
